// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://torwzztnpzvzagvdvgpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcnd6enRucHp2emFndmR2Z3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDExODEsImV4cCI6MjA1ODUxNzE4MX0.rsOPuaLpScZ6zbpch6VEhVCdo28mxlbIjU1O8g3WuYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);